---
- name: Deploy VulnHub Challenge VM
  hosts: proxmox_hostx
  vars:
    vm_id: "{{ 2000 + (challenge_id | int) }}"
    vulnhub_machine: "{{ challenge_name }}"

  tasks:
    - name: Clone VM dari template VulnHub
      community.general.proxmox:
        api_user: root@pam
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        node: pve
        name: "ctf-{{ vulnhub_machine }}-{{ vm_id }}"
        clone: "template-{{ vulnhub_machine }}"
        vmid: "{{ vm_id }}"
        storage: local-lvm
        timeout: 300
        # Network config (sesuai kebutuhan VulnHub)
        net: '{"net0":"virtio,bridge=vmbr0,firewall=1"}'

    - name: Start VM
      community.general.proxmox:
        api_user: root@pam
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        vmid: "{{ vm_id }}"
        state: started

    - name: Dapatkan IP VM
      community.general.proxmox:
        api_user: root@pam
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        vmid: "{{ vm_id }}"
      register: vm_info

    - name: Simpan info ke database
      uri:
        url: "{{ fastapi_url }}/challenges/{{ challenge_id }}/deployed"
        method: POST
        body:
          vm_id: "{{ vm_id }}"
          ip_address: "{{ vm_info.vm_data.networks[0].ip }}"
          status: "running"